### ISSUE TITLE
ERROR could not load image "xpanes_space.png", creating dummy image

### ISSUE THREAD

**Issue by Soundtoxin** [minetest-mods/xdecor#123]
```
2020-07-19 02:36:34: ERROR[Main]: generateImage(): Could not load image "xpanes_space.png" while building texture; Creating a dummy image
```
Mod is installed on a dedicated server, error is seen on the client.

**Comment by lenikun-sempai** [comment]
New here. Don't know how this works, but I have the same error. Ideas? :(  I really want this mod

![error](https://user-images.githubusercontent.com/68709096/88327865-2fd49d80-cced-11ea-9074-754988f79090.jpg)

**Comment by CHJ85** [comment]
I know this is an old one, but how exactly do I fix this issue?
In what folder do I put the blank png to replace xplanes_space.png?

**Comment by SmallJoker** [comment]
@CHJ85 `xpanes_space.png` should no longer be used by xdecor. Please update your mod to the current version and check whether the issue persists.

**Comment by CHJ85** [comment]
I updated all my mods. Now I'm getting all sorts of dependency errors about mods that don't even exist, such as infrastructure, lavalamp, inbox and computer. I don't know. This game seems to have a lot of issues. Like every time there's a new mod version, it breaks something else. That's why I stayed on the old versions because then I only had to deal with a couple of errors.
