### ISSUE TITLE
Craft reziep conflict with castles mod

### ISSUE THREAD

**Issue by adrido** [minetest-mods/xdecor#73]
xdecor:rope is crafted out of 3 farming:cotton
and castle:ropes is using the same recipe

https://github.com/minetest-mods/castle/issues/30

**Comment by kilbith** [comment]
Thanks for the info but that's not my problem.

**Comment by adrido** [comment]
And whos problem is it then?

**Comment by kilbith** [comment]
I highly doubt there's such a rule because it's expected and unavoidable to get mod conflicts with a wide plurality of mods.

And in case there's such a rule, I'm not emotionally tied to this organization and it's no big deal for me to leave if requested. Anyway, I'm just focusing on my mods (not a hobby anymore, more like a responsability) and this is already enough of a pain for a volunteer.

**Comment by adrido** [comment]
Yeah I know that maintaining mods doesn't make much fun, especially if people like me sending bug reports like this. But you are not alone in that team, and if you leave this issue open maybe someone else want to fix it some day.

**Comment by kilbith** [comment]
I simply impose my veto for changes in `xdecor` because other mods conflicting with it, except if these mods are : **1.** from Minetest Game or **2.** popular and in line with the vision of `xdecor`. Which is not the case for `castle`, therefore I can't consider it as a notable equal.
